server:
  port: 8080
  servlet:
    session:
    timeout: PT8H
  undertow:
    io-threads: 16
    worker-threads: 400
    buffer-size: 1024
    direct-buffers: true

spring:
  datasource:
    url: jdbc:mysql://47.97.158.11:3306/tableCards?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    #url: jdbc:mysql://127.0.0.1:3306/kinect?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: Sss991126/
    #password: zucciot421
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validaionQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true,druid.stat.slowSqlMills=500



jwt-config:
  expire-time: 86400000
  token-secret: ILikeFitness

